### ISSUE TITLE
Projektfortschritt nicht erkenntlich

### ISSUE THREAD

**Issue by tigion** [S78942/SE-Hochschulpartnerschaften#33]
Hallo, wenn ich mir die seit Dezember/Januar geplanten Issues/Iterationen und den bisher versionierten Quellcode anschaue ist mir kein Projektfortschritt ersichtlich. In den anderen Gruppen geht es stetig voran.

Erste Anforderungen und Use-Cases an die Software stehen ja und könnten Stück für Stück, per Issues und Iterationen geplant, bearbeitet werden. Lösungen für Online-Meetings bietet die HTW einige an und darüber hinaus gibt es noch einige mehr Möglichkeiten.
Auch während der normalen Studienzeit hätte die Bearbeitung vom Team hauptsächlich in der vom Studium geplanten heimischen Selbststudienzeit stattgefunden.

- Wie ist der aktuelle Stand?
- Klappt die Kommunikation im Team?
- Sind schon Online-Meetings (mit Protokoll) durchgeführt worden?
- Sind mit dem Team die anstehenden Iterationen und Workitems gewichtet und zugeteilt worden?
- Weiß jeder was er in der aktuellen Iteration zu tun hat?
- Werden Probleme im Team thematisiert?
- Gibt es andere Gründe, welche noch nicht kommuniziert worden?

Oder werden die Ergebnisse nur aktuell nicht mit dem Repository synchronisiert?

Wer hat denn die Praktika Teil 4 und Teil 5 bearbeitet?
- [ ] @lukassiegert 
- [ ] @maily511 
- [ ] @Manuel279 
- [ ] @pigutsche 
- [ ] @rinde42 
- [ ] @s78826 
- [ ] @S78942 
- [ ] @viethuong12

**Comment by S78942** [comment]
Wir machen nächste Woche ein Meeting und dann kann ich Sie über den Verlauf/Stand informieren. Es wird voraussichtlich alle 2 Wochen ein Meeting geben. 
Desweiteren möchte ich noch kurz auf Ihr Statement "Auch während der normalen Studienzeit hätte die Bearbeitung vom Team hauptsächlich in der vom Studium geplanten heimischen Selbststudien-zeit stattgefunden." 
Es ist nun mal kein normales Semester und wir haben nicht nur ein Beleg sondern einige zu bearbeiten , was viele Stunden in Anspruch nimmt und vergessen sollten Sie auch nicht , dass einige Kinder haben und die Kita geschlossen hat. @tigion

**Comment by tigion** [comment]
Alles gut, die aktuelle Situation ist natürlich, und vor allem für alle mit Familie, fordernder. Ich möchte nur nicht, dass sich das Projekt **unkommuniziert** verzögert bzw. Hürden/Probleme zu spät angegangen werden und diese letztendlich sich nachteilig auf das Team auswirken.

Vielleicht empfiehlt es sich für zukünftige Iterationen kürzere Zeitfenster von 2 Wochen (was gut zu den zweiwöchigen Meetings passen würde) mit weniger Workitems (Issues) zu planen und dafür die Teammitglieder stärker auf diese wenigen Workitems zu bündeln. Die Rollenverteilung soll eher eine Verantwortlichkeit (stärkeres Beschäftigen mit dem zugehörigen Thema) sein und trotzdem Raum (je nach Auslastung) für die Mitarbeit an den anstehenden Workitems bieten.

Bleibt gesund. 😷
