### ISSUE TITLE
Einladung Coach zum nächsten Gruppenmeeting

### ISSUE THREAD

**Issue by tigion** [S78942/SE-Hochschulpartnerschaften#4]
Idealerweise ohne Auftraggeber, um einen Eindruck ihrer Gruppe und Herangehensweise zu bekommen.

Ist kein Treffen mehr dieses Jahr geplant, wäre auch ein Treffen in kleinerer Runde (gern auch im Praktikum) möglich.

Interessieren würde mich:
- ihre Findung als Team
- ihre ersten Erfahrungen mit dem Kunden
- ihre ersten Erkenntnisse

**Comment by S78942** [comment]
Am Donnerstag, 19.12.2019 / Zimmer S230 werden wir zusammentreffen @tigion

**Comment by tigion** [comment]
Die Uhrzeit wäre noch interessant, um zu schauen ob ich Zeit habe.

**Comment by S78942** [comment]
15 Uhr sry :D @tigion
